### ISSUE TITLE
Workflow run failed to to missing log file

### ISSUE THREAD

**Issue by chnixi** [pitt-crc/bank#358]
While creating a new pull request, the workflow run failed at the build documentation stage because the file '/ihome/crc/bank/crc_bank.log' cannot be found.

**Comment by Comeani** [comment]
Hey Cheng, I believe this is related to #323, basically the CI is broken for additions to the bank because the settings are hardcoded to make the application work in production. We've been working around this by testing locally and otherwise deferring major changes to the bank in favor of switching to keystone. 

I can do some testing on your PRs and give them a review.

**Comment by Comeani** [comment]
This would be resolved by fixing #323, but I don't think we will get to it now that we are focused on keystone
